=== mbaggott/xml-manipulation-json/output/output.dtd
<!ELEMENT authors (author+)>
<!ELEMENT author (name,born-died,nationality,biography,artworks+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT born-died (#PCDATA)>
<!ELEMENT nationality (#PCDATA)>
<!ELEMENT biography (#PCDATA)>
<!ELEMENT artworks (artwork+)>
<!ATTLIST artworks form CDATA #REQUIRED>
<!ELEMENT artwork (title,technique,location)>
<!ATTLIST artwork date CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT technique (#PCDATA)>
<!ELEMENT location (#PCDATA)>

=== mbaggott/xml-manipulation-json/bin/output.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE authors SYSTEM "output.dtd">
<authors>
  <author>
    <name>AMADEO, Giovanni Antonio</name>
    <born-died>b. ca. 1447, Pavia, d. 1522, Milano</born-died>
    <nationality>Italian</nationality>
    <biography>Giovanni Antonio Amadeo was an Italian early Renaissance sculptor, architect, and engineer. In 1466 he was engaged as a sculptor, with his brother Protasio, at the famous Certosa, near Pavia. He was a follower of the style of Bramantino of Milan, and he represents, like him, the Lombard direction of the Renaissance. He practised cutting deeply into marble, arranging draperies in cartaceous folds, and treating surfaces flatly even when he sculptured figures in high relief. Excepting in these technical points he differed from his associates completely, and so far surpassed them that he may be ranked with the great Tuscan artists of his time, which can be said of hardly any other North-Italian sculptor.</biography>
    <artworks form="architecture">
      <artwork date="1473">
        <title>Fa&#xE7;ade of the church</title>
        <technique>Marble</technique>
        <location>Certosa, Pavia</location>
      </artwork>
    </artworks>
  </author>
  <author>
    <name>ANDREA DEL CASTAGNO</name>
    <born-died>b. 1423, Castagno, d. 1457, Firenze</born-died>
    <nationality>Italian</nationality>
    <biography>Andrea del Castagno (or Andrea di Bartolo di Bargilla) was an Italian painter from Florence, influenced chiefly by Tommaso Masaccio and Giotto di Bondone. His works include frescoes in Sant'Apollonia in Florence and the painted equestrian monument of Niccol&#xF2; da Tolentino (1456) in the Cathedral in Florence. He in turn influenced the Ferrarese school of Cosm&#xE8; Tura, Francesco del Cossa and Ercole de' Roberti.</biography>
    <artworks form="painting">
      <artwork date="1450">
        <title>Our Lady of the Assumption with Sts Miniato and Julian</title>
        <technique>Panel, 150 x 158 cm</technique>
        <location>Staatliche Museen, Berlin</location>
      </artwork>
    </artworks>
  </author>
  <author>
    <name>ANTICO</name>
    <born-died>b. ca. 1460, Mantova, d. 1528, Mantova</born-died>
    <nationality>Italian</nationality>
    <biography>Italian sculptor, goldsmith, and medallist. His nickname derived from his classically inspired bronze statuettes, many of which were versions of famous antique statues such as the Apollo Belvedere (he also restored ancient sculpture). He visited Rome in the 1490s, but worked mainly in and around Mantua, particularly for members of the Gonzaga family and Isabella d'Este.</biography>
    <artworks form="sculpture">
      <artwork date="1490">
        <title>Eros</title>
        <technique>Bronze, height: 90 cm</technique>
        <location>Museo Nazionale del Bargello, Florence</location>
      </artwork>
    </artworks>
  </author>
  <author>
    <name>BARTOLOMEO DELLA GATTA</name>
    <born-died>b. 1448, Firenze, d. 1502, Firenze</born-died>
    <nationality>Italian</nationality>
    <biography>Bartolomeo della Gatta, born Pietro di Antonio Dei, was an Italian (Florentine) painter, illuminator, and architect. He was the son of a goldsmith. Bartolomeo eventually became Abbot of San Clemente in Arezzo. He died in 1502 and was buried in the Abbey of San Clemente.</biography>
    <artworks form="painting">
      <artwork date="1479">
        <title>St Roch in front of the Fraternita dei Laici in Arezzo</title>
        <technique>Tempera on panel, 215 x 115 cm</technique>
        <location>Museo Statale d'Arte Medievale e Moderna, Arezzo</location>
      </artwork>
    </artworks>
  </author>
  <author>
    <name>BARTOLOMEO, Fra</name>
    <born-died>b. 1472, Firenze, d. 1517, Pian' di Mugnone</born-died>
    <nationality>Italian</nationality>
    <biography>Fra Bartolomeo or Fra Bartolommeo (di Pagholo), also known as Baccio della Porta, was an Italian Renaissance painter of religious subjects. Fra Bartolomeo's compositions are remarkable for skill in the massing of light and shade, richness and delicacy of colouring, and for the admirable drapery of the figures, Bartolomeo having been the first to introduce and use the lay-figure with joints.</biography>
    <artworks form="painting">
      <artwork date="1497">
        <title>Annunciation</title>
        <technique>Panel, 176 x 170 cm</technique>
        <location>Duomo, Volterra</location>
      </artwork>
      <artwork date="1499">
        <title>Last Judgment</title>
        <technique>Detached fresco</technique>
        <location>Museo di San Marco, Florence</location>
      </artwork>
    </artworks>
  </author>
  <author>
    <name>BELLINI, Gentile</name>
    <born-died>b. ca. 1429, Venezia, d. 1507, Venezia</born-died>
    <nationality>Italian</nationality>
    <biography>Gentile Bellini was an Italian painter. Born in Venice, the son of the painter Jacopo Bellini, he was christened Gentile after Jacopo's master, Gentile da Fabriano. From 1474 he was the official portrait artist for the Doges of Venice. Gentile was trained by his father, Jacopo Bellini, a painter who introduced Renaissance concerns and motifs into Venice. </biography>
    <artworks form="painting">
      <artwork date="1465">
        <title>The Blessed Lorenzo Giustiniani</title>
        <technique>Tempera on canvas, 221 x 155 cm</technique>
        <location>Gallerie dell'Accademia, Venice</location>
      </artwork>
      <artwork date="1496">
        <title>Procession in Piazza S. Marco</title>
        <technique>Tempera and oil on canvas, 367 x 745 cm</technique>
        <location>Gallerie dell'Accademia, Venice</location>
      </artwork>
      <artwork date="1500">
        <title>Miracle of the Cross at the Bridge of San Lorenzo</title>
        <technique>Tempera on canvas, 323 x 430 cm</technique>
        <location>Gallerie dell'Accademia, Venice</location>
      </artwork>
    </artworks>
  </author>
  <author>
    <name>BELLINI, Giovanni</name>
    <born-died>b. ca. 1426, Venezia, d. 1516, Venezia</born-died>
    <nationality>Italian</nationality>
    <biography>Giovanni Bellini was an Italian Renaissance painter, probably the best known of the Bellini family of Venetian painters. His father was Jacopo Bellini, his brother was Gentile Bellini, and his brother-in-law was Andrea Mantegna. He is considered to have revolutionized Venetian painting, moving it towards a more sensuous and colouristic style. Through the use of clear, slow-drying oil paints, Giovanni created deep, rich tints and detailed shadings. His sumptuous coloring and fluent, atmospheric landscapes had a great effect on the Venetian painting school, especially on his pupils Giorgione and Titian.</biography>
    <artworks form="painting">
      <artwork date="1472">
        <title>Piet&#xE0;</title>
        <technique>Tempera on canvas, 115 x 317 cm</technique>
        <location>Palazzo Ducale, Venice</location>
      </artwork>
      <artwork date="1475">
        <title>Madonna Enthroned Adoring the Sleeping Child</title>
        <technique>Tempera on wood, 120 x 65 cm</technique>
        <location>Gallerie dell'Accademia, Venice</location>
      </artwork>
      <artwork date="1487">
        <title>Madonna degli Alberetti</title>
        <technique>Oil on panel, 74 x 58 cm</technique>
        <location>Gallerie dell'Accademia, Venice</location>
      </artwork>
      <artwork date="1487">
        <title>Madonna with the Child</title>
        <technique>Oil on panel, 75 x 59 cm</technique>
        <location>Museu de Arte, S&#xE3;o Paolo</location>
      </artwork>
      <artwork date="1488">
        <title>Barbarigo Altarpiece</title>
        <technique>Oil on canvas, 200 x 320 cm</technique>
        <location>San Pietro Martire, Murano</location>
      </artwork>
      <artwork date="1488">
        <title>Frari Triptych</title>
        <technique>Oil on panel</technique>
        <location>Santa Maria Gloriosa dei Frari, Venice</location>
      </artwork>
      <artwork date="1490">
        <title>Sacred Conversation</title>
        <technique>Oil on panel, 77 x 104 cm</technique>
        <location>Museo del Prado, Madrid</location>
      </artwork>
      <artwork date="1500">
        <title>Portrait of a Young Man</title>
        <technique>Oil on wood, 31 x 26 cm</technique>
        <location>Galleria degli Uffizi, Florence</location>
      </artwork>
    </artworks>
  </author>
  <author>
    <name>BELLINI, Jacopo</name>
    <born-died>b. ca. 1400, Venezia, d. 1470, Venezia</born-died>
    <nationality>Italian</nationality>
    <biography>Jacopo Bellini was an Italian painter. Jacopo was one of the founders of the Renaissance style of painting in Venice and northern Italy. His sons Gentile and Giovanni Bellini, and his son-in-law Andrea Mantegna, were also famous painters.</biography>
    <artworks form="painting">
      <artwork date="1450">
        <title>Madonna and Child</title>
        <technique>Tempera on wood, 111 x 62 cm</technique>
        <location>Galleria degli Uffizi, Florence</location>
      </artwork>
      <artwork date="1450">
        <title>Madonna and Child</title>
        <technique>Tempera on wood, 73 x 57 cm</technique>
        <location>Galleria degli Uffizi, Florence</location>
      </artwork>
    </artworks>
  </author>
  <author>
    <name>BENEDETTO DA MAIANO</name>
    <born-died>b. 1442, Firenze, d. 1497, Firenze</born-died>
    <nationality>Italian</nationality>
    <biography>Benedetto da Maiano, early Renaissance sculptor, whose work is characterized by its decorative elegance and realistic detail. Benedetto da Maiano, or Benedetto da Majano, was the younger brother of Giuliano da Maiano and his partner in their Florence studio. Benedetto is credited with designing the first story of the Palazzo Strozzi, although according to some sources, Giuliano da Sangallo was the actual designer of the building.</biography>
    <artworks form="painting">
