=== mbaggott/xml-manipulation-json/resources/artworks.dtd
<!ELEMENT artworks (artwork+)>
<!ELEMENT artwork (title,author,date,technique,location,form,type)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT technique (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT form (#PCDATA)>
<!ELEMENT type (#PCDATA)>

=== mbaggott/xml-manipulation-json/bin/artworks.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE artworks SYSTEM "artworks.dtd">
<artworks>
  <artwork>
    <title>Adoration of the Magi</title>
    <author>GHIRLANDAIO, Domenico</author>
    <date>1487</date>
    <technique>Tempera on wood, diameter: 171 cm</technique>
    <location>Galleria degli Uffizi, Florence</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Adoration of the Magi</title>
    <author>GHIRLANDAIO, Domenico</author>
    <date>1488</date>
    <technique>Tempera on wood, 285 x 240 cm</technique>
    <location>Spedale degli Innocenti, Florence</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Adoration of the Magi</title>
    <author>LIPPI, Filippino</author>
    <date>1496</date>
    <technique>Oil on wood, 258 x 243 cm</technique>
    <location>Galleria degli Uffizi, Florence</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Adoration of the Magi</title>
    <author>COSTA, Lorenzo the Elder</author>
    <date>1499</date>
    <technique>Oil on panel, 75 x 181 cm</technique>
    <location>Pinacoteca di Brera, Milan</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Advent and Triumph of Christ</title>
    <author>MEMLING, Hans</author>
    <date>1480</date>
    <technique>Oil on wood, 81 x 189 cm</technique>
    <location>Alte Pinakothek, Munich</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Agony in the Garden</title>
    <author>DONATELLO</author>
    <date>1465</date>
    <technique>Bronze</technique>
    <location>Church of San Lorenzo, Florence</location>
    <form>sculpture</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Allegory</title>
    <author>PIERO DI COSIMO</author>
    <date>1500</date>
    <technique>Panel</technique>
    <location>National Gallery of Art, Washington</location>
    <form>painting</form>
    <type>mythological</type>
  </artwork>
  <artwork>
    <title>Altarpiece</title>
    <author>FOPPA, Vincenzo</author>
    <date>1476</date>
    <technique>Tempera on panel</technique>
    <location>Pinacoteca di Brera, Milan</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Altarpiece</title>
    <author>VIVARINI, Bartolomeo</author>
    <date>1485</date>
    <technique>Tempera and oil on panel, 236 x 198 (overall)</technique>
    <location>Museum of Fine Arts, Boston</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Altarpiece of the Sts Vincent, James, and Eustace</title>
    <author>POLLAIUOLO, Antonio del</author>
    <date>1468</date>
    <technique>Tempera on wood, 172 x 179 cm</technique>
    <location>Galleria degli Uffizi, Florence</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Annunciation</title>
    <author>CHRISTUS, Petrus</author>
    <date>1452</date>
    <technique>Wood, 85,5 x 54,8 cm</technique>
    <location>Groeninge Museum, Bruges</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Annunciation</title>
    <author>TURA, Cosmè</author>
    <date>1469</date>
    <technique>Tempera on canvas, 349 x 305 cm</technique>
    <location>Museo del Duomo, Ferrara</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Annunciation</title>
    <author>BOTTICELLI, Sandro</author>
    <date>1481</date>
    <technique>Fresco, 243 x 550 cm</technique>
    <location>Galleria degli Uffizi, Florence</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Annunciation</title>
    <author>GHIRLANDAIO, Domenico</author>
    <date>1482</date>
    <technique>Fresco</technique>
    <location>Collegiata di Santa Maria Maggiore, Spello</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Annunciation</title>
    <author>BARTOLOMEO, Fra</author>
    <date>1497</date>
    <technique>Panel, 176 x 170 cm</technique>
    <location>Duomo, Volterra</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Annunciation and Nativity</title>
    <author>CHRISTUS, Petrus</author>
    <date>1452</date>
    <technique>Oak, 134 x 56 cm</technique>
    <location>Staatliche Museen, Berlin</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Annunciation with St Emidius</title>
    <author>CRIVELLI, Carlo</author>
    <date>1486</date>
    <technique>Oil on wood transferred to canvas, 207 x 147 cm</technique>
    <location>National Gallery, London</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Apotheosis of St Ursula</title>
    <author>CARPACCIO, Vittore</author>
    <date>1491</date>
    <technique>Tempera on canvas, 481 x 336 cm</technique>
    <location>Gallerie dell'Accademia, Venice</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Apparition of The Virgin to St Bernard</title>
    <author>LIPPI, Filippino</author>
    <date>1486</date>
    <technique>Oil on panel, 210 x 195 cm</technique>
    <location>Church of Badia, Florence</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Arrest of Christ</title>
    <author>BIAGIO D'ANTONIO</author>
    <date>1482</date>
    <technique>Fresco</technique>
    <location>Cappella Sistina, Vatican</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Assumption of the Virgin</title>
    <author>GOZZOLI, Benozzo</author>
    <date>1484</date>
    <technique>Transferred fresco</technique>
    <location>Biblioteca Comunale, Castelfiorentino</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Assumption of the Virgin with Four Saints</title>
    <author>PERUGINO, Pietro</author>
    <date>1500</date>
    <technique>Oil on wood, 415 x 246 cm</technique>
    <location>Galleria degli Uffizi, Florence</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Bacchus</title>
    <author>MICHELANGELO Buonarroti</author>
    <date>1497</date>
    <technique>Marble, height: 203 cm</technique>
    <location>Museo Nazionale del Bargello, Florence</location>
    <form>sculpture</form>
    <type>mythological</type>
  </artwork>
  <artwork>
    <title>Barbarigo Altarpiece</title>
    <author>BELLINI, Giovanni</author>
    <date>1488</date>
    <technique>Oil on canvas, 200 x 320 cm</technique>
    <location>San Pietro Martire, Murano</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Bathsheba</title>
    <author>MEMLING, Hans</author>
    <date>1485</date>
    <technique>Oil on wood, 191 x 84 cm</technique>
    <location>Staatsgalerie, Stuttgart</location>
    <form>painting</form>
    <type>mythological</type>
  </artwork>
  <artwork>
    <title>Battle between the Gonzaga and the Bonacolsi</title>
    <author>MORONE, Domenico</author>
    <date>1494</date>
    <technique>Oil on wood</technique>
    <location>Palazzo Ducale, Mantua</location>
    <form>painting</form>
    <type>historical</type>
  </artwork>
  <artwork>
    <title>Birth of Mary</title>
    <author>GOZZOLI, Benozzo</author>
    <date>1491</date>
    <technique>Transferred fresco</technique>
    <location>Biblioteca Comunale, Castelfiorentino</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Calling of the Apostles</title>
    <author>GHIRLANDAIO, Domenico</author>
    <date>1481</date>
    <technique>Fresco, 349 x 570 cm</technique>
    <location>Cappella Sistina, Vatican</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Charity</title>
    <author>POLLAIUOLO, Piero del</author>
    <date>1470</date>
    <technique>Tempera on wood, 167 x 88 cm</technique>
    <location>Galleria degli Uffizi, Florence</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Christ Giving His Blessing</title>
    <author>MEMLING, Hans</author>
    <date>1478</date>
    <technique>Oil on oak panel, 38,1 x 28,2 cm</technique>
    <location>Norton Simon Museum of Art, Pasadena</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Christ Giving His Blessing</title>
    <author>MEMLING, Hans</author>
    <date>1481</date>
    <technique>Oil on oak panel, 34,8 x 26,2 cm</technique>
    <location>Museum of Fine Arts, Boston</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Circe and Ulysses</title>
    <author>WOLGEMUT, Michael</author>
    <date>1493</date>
    <technique>Woodcut, 121 x 156 mm</technique>
    <location>Various collections</location>
    <form>painting</form>
    <type>mythological</type>
  </artwork>
  <artwork>
    <title>Combined Coat-of-Arms of the Tucher and Rieter Families</title>
    <author>DÜRER, Albrecht</author>
    <date>1499</date>
    <technique>Oil on panel, 28 x 24 cm</technique>
    <location>Schlossmuseum, Weimar</location>
    <form>painting</form>
    <type>mythological</type>
  </artwork>
  <artwork>
    <title>Conversano Polyptych</title>
    <author>VIVARINI, Bartolomeo</author>
    <date>1475</date>
    <technique>Tempera on wood, 157 x 271</technique>
    <location>Gallerie dell'Accademia, Venice</location>
    <form>painting</form>
    <type>religious</type>
  </artwork>
  <artwork>
    <title>Coronation of the Virgin</title>
    <author>POLLAIUOLO, Piero del</author>
    <date>1483</date>
