=== mbaggott/xml-manipulation-json/resources/authors.dtd
<!ELEMENT authors (author+)>
<!ELEMENT author (name,born-died,nationality,biography)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT born-died (#PCDATA)>
<!ELEMENT nationality (#PCDATA)>
<!ELEMENT biography (#PCDATA)>

=== mbaggott/xml-manipulation-json/bin/authors.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE authors SYSTEM "authors.dtd">
<authors>
  <author>
    <name>AMADEO, Giovanni Antonio</name>
    <born-died>b. ca. 1447, Pavia, d. 1522, Milano</born-died>
    <nationality>Italian</nationality>
    <biography>Giovanni Antonio Amadeo was an Italian early Renaissance sculptor, architect, and engineer. In 1466 he was engaged as a sculptor, with his brother Protasio, at the famous Certosa, near Pavia. He was a follower of the style of Bramantino of Milan, and he represents, like him, the Lombard direction of the Renaissance. He practised cutting deeply into marble, arranging draperies in cartaceous folds, and treating surfaces flatly even when he sculptured figures in high relief. Excepting in these technical points he differed from his associates completely, and so far surpassed them that he may be ranked with the great Tuscan artists of his time, which can be said of hardly any other North-Italian sculptor.</biography>
  </author>
  <author>
    <name>ANDREA DEL CASTAGNO</name>
    <born-died>b. 1423, Castagno, d. 1457, Firenze</born-died>
    <nationality>Italian</nationality>
    <biography>Andrea del Castagno (or Andrea di Bartolo di Bargilla) was an Italian painter from Florence, influenced chiefly by Tommaso Masaccio and Giotto di Bondone. His works include frescoes in Sant'Apollonia in Florence and the painted equestrian monument of Niccolò da Tolentino (1456) in the Cathedral in Florence. He in turn influenced the Ferrarese school of Cosmè Tura, Francesco del Cossa and Ercole de' Roberti.</biography>
  </author>
  <author>
    <name>ANTICO</name>
    <born-died>b. ca. 1460, Mantova, d. 1528, Mantova</born-died>
    <nationality>Italian</nationality>
    <biography>Italian sculptor, goldsmith, and medallist. His nickname derived from his classically inspired bronze statuettes, many of which were versions of famous antique statues such as the Apollo Belvedere (he also restored ancient sculpture). He visited Rome in the 1490s, but worked mainly in and around Mantua, particularly for members of the Gonzaga family and Isabella d'Este.</biography>
  </author>
  <author>
    <name>BARTOLOMEO DELLA GATTA</name>
    <born-died>b. 1448, Firenze, d. 1502, Firenze</born-died>
    <nationality>Italian</nationality>
    <biography>Bartolomeo della Gatta, born Pietro di Antonio Dei, was an Italian (Florentine) painter, illuminator, and architect. He was the son of a goldsmith. Bartolomeo eventually became Abbot of San Clemente in Arezzo. He died in 1502 and was buried in the Abbey of San Clemente.</biography>
  </author>
  <author>
    <name>BARTOLOMEO, Fra</name>
    <born-died>b. 1472, Firenze, d. 1517, Pian' di Mugnone</born-died>
    <nationality>Italian</nationality>
    <biography>Fra Bartolomeo or Fra Bartolommeo (di Pagholo), also known as Baccio della Porta, was an Italian Renaissance painter of religious subjects. Fra Bartolomeo's compositions are remarkable for skill in the massing of light and shade, richness and delicacy of colouring, and for the admirable drapery of the figures, Bartolomeo having been the first to introduce and use the lay-figure with joints.</biography>
  </author>
  <author>
    <name>BELLINI, Gentile</name>
    <born-died>b. ca. 1429, Venezia, d. 1507, Venezia</born-died>
    <nationality>Italian</nationality>
    <biography>Gentile Bellini was an Italian painter. Born in Venice, the son of the painter Jacopo Bellini, he was christened Gentile after Jacopo's master, Gentile da Fabriano. From 1474 he was the official portrait artist for the Doges of Venice. Gentile was trained by his father, Jacopo Bellini, a painter who introduced Renaissance concerns and motifs into Venice. </biography>
  </author>
  <author>
    <name>BELLINI, Giovanni</name>
    <born-died>b. ca. 1426, Venezia, d. 1516, Venezia</born-died>
    <nationality>Italian</nationality>
    <biography>Giovanni Bellini was an Italian Renaissance painter, probably the best known of the Bellini family of Venetian painters. His father was Jacopo Bellini, his brother was Gentile Bellini, and his brother-in-law was Andrea Mantegna. He is considered to have revolutionized Venetian painting, moving it towards a more sensuous and colouristic style. Through the use of clear, slow-drying oil paints, Giovanni created deep, rich tints and detailed shadings. His sumptuous coloring and fluent, atmospheric landscapes had a great effect on the Venetian painting school, especially on his pupils Giorgione and Titian.</biography>
  </author>
  <author>
    <name>BELLINI, Jacopo</name>
    <born-died>b. ca. 1400, Venezia, d. 1470, Venezia</born-died>
    <nationality>Italian</nationality>
    <biography>Jacopo Bellini was an Italian painter. Jacopo was one of the founders of the Renaissance style of painting in Venice and northern Italy. His sons Gentile and Giovanni Bellini, and his son-in-law Andrea Mantegna, were also famous painters.</biography>
  </author>
  <author>
    <name>BENEDETTO DA MAIANO</name>
    <born-died>b. 1442, Firenze, d. 1497, Firenze</born-died>
    <nationality>Italian</nationality>
    <biography>Benedetto da Maiano, early Renaissance sculptor, whose work is characterized by its decorative elegance and realistic detail. Benedetto da Maiano, or Benedetto da Majano, was the younger brother of Giuliano da Maiano and his partner in their Florence studio. Benedetto is credited with designing the first story of the Palazzo Strozzi, although according to some sources, Giuliano da Sangallo was the actual designer of the building.</biography>
  </author>
  <author>
    <name>BERGOGNONE, Ambrogio</name>
    <born-died>b. ca. 1453, Fossano, d. 1523, Milano</born-died>
    <nationality>Italian</nationality>
    <biography>Italian painter born in Milan and active there during most of his career. Mentioned as a master in the Milanese painters' register of 1481 he began to call himself Bergognone or Borgognone from 1495 . He was a pupil of Vincenzo Foppa to whose serene style and composition he remained true. His careful rendition of background detail also suggests a Flemish influence, while Provencal painting may be seen as a source for his figure style. </biography>
  </author>
  <author>
    <name>BERMEJO, Bartolomé</name>
    <born-died>b. ca. 1440, Cordova, d. ca. 1500, Barcelona</born-died>
    <nationality>Spanish</nationality>
    <biography>Bartolomé Bermejo was a Spanish painter who adopted Flemish painting techniques and conventions. A cultivator of the Flemish style, who was considered the finest painter in Spain before El Greco. Bermejo helped introduce Renaissance style to Spain, and his work was emulated by many painters of his era.</biography>
  </author>
  <author>
    <name>BERRUGUETE, Pedro</name>
    <born-died>b. 1450, Paredes de Nava, d. 1504, Avila</born-died>
    <nationality>Spanish</nationality>
    <biography>Pedro Berruguete was a Spanish painter; his art is regarded as a transitional style between gothic and Renaissance. Born in Paredes de Nava, Spain, he went to Italy in 1480 and worked in Federigo da Montefeltro's court in Urbino, where he could see some works by Melozzo da Forlì. He came back to Spain in 1482 and painted in several cities, such as Sevilla, Toledo and Ávila. He was the father of an important sculptor, Alonso Berruguete, considered the most important sculptor in Renaissance Spain.</biography>
  </author>
  <author>
    <name>BERTOLDO DI GIOVANNI</name>
    <born-died>b. ca. 1420, d. 1491, Poggio a Caiano</born-died>
    <nationality>Italian</nationality>
    <biography>Bertoldo di Giovanni was an Italian Renaissance sculptor and medalist who was a student of Donatello and a teacher of Michelangelo. Bertoldo and Bartolomeo Bellano of Padua were the two bronze specialists associated with Donatello, and Bertoldo's earliest known work was executed between 1460 and 1470 on the San Lorenzo pulpits, which had been left unfinished by Donatello. He had the major responsibility for the frieze and also executed work on the relief of the entombment.</biography>
  </author>
  <author>
    <name>BIAGIO D'ANTONIO</name>
    <born-died>b. 1446, Firenze, d. 1515, Firenze</born-died>
    <nationality>Italian</nationality>
    <biography>Biagio d'Antonio, also Biagio Tucci, was an Italian Renaissance painter whose style was influenced by Fra Filippo Lippi, Andrea Verrocchio and Ghirlandaio. For much of the last quarter of the fifteenth century Biagio was active in Faenza, but his style continued to reflect Florentine innovations. His paintings also demonstrate influences -- particularly in the decorative elements -- from early Netherlandish painting.</biography>
  </author>
  <author>
    <name>BOCCATI, Giovanni di Piermatteo</name>
    <born-died>b. ca. 1420, Camerino, d. 1487</born-died>
    <nationality>Italian</nationality>
    <biography>Giovanni di Pier Matteo Boccati, who was born in Camerino, was documented as an associate of Filippo Lippi in Florence in 1443.  He became a citizen of Perugia in 1445, on the basis of an application in which he announced his intention to establish a workshop in the city. </biography>
  </author>
  <author>
    <name>BONFIGLI, Benedetto</name>
    <born-died>b. ca. 1420, Perugia, d. 1496, Perugia</born-died>
    <nationality>Italian</nationality>
    <biography>Benedetto Bonfigli was an Italian painter of the Quattrocento born in Perugia, and active around Umbria. He is also known as Buonfiglio. He was the teacher of the painter Pietro Perugino.</biography>
  </author>
  <author>
    <name>BOTTICELLI, Sandro</name>
    <born-died>b. 1445, Firenze, d. 1510, Firenze</born-died>
    <nationality>Italian</nationality>
